2025-09-24 15:55:53 WARNING GPU is not available. Check your Pytorch installation.
2025-09-24 15:55:53 INFO >>>>>>> training start <<<<<<<
2025-09-24 15:55:53 INFO Training iter0 save to: storage/results/MIMIC_III/Ada_MSHyper/Ada_MSHyper/72_3/2025_0924_1555/iter0
2025-09-24 15:55:54 DEBUG getting train set of MIMIC_III in tsdm format
2025-09-24 15:56:01 DEBUG self.configs.seq_len_max_irr=72
2025-09-24 15:56:01 DEBUG self.configs.pred_len_max_irr=3
2025-09-24 15:56:01 DEBUG getting val set of MIMIC_III in tsdm format
2025-09-24 15:56:09 INFO Train stage 1/1 starts.
Epochs:   0%|          | 0/300 [00:00<?, ?it/s]
Training:   0%|          | 0/537 [00:00<?, ?it/s][A
                                                 [AEpochs:   0%|          | 0/300 [00:00<?, ?it/s]
2025-09-24 15:56:09 ERROR No CUDA GPUs are available
Traceback (most recent call last):
  File "/mnt/home/khaledm/PyOmniTS/main.py", line 74, in <module>
    main()
  File "/mnt/home/khaledm/PyOmniTS/main.py", line 61, in main
    exp.train()
  File "/mnt/home/khaledm/PyOmniTS/exp/exp_main.py", line 285, in train
    batch = {k: v.to(f"cuda:{self.configs.gpu_id}") for k, v in batch.items()}
  File "/mnt/home/khaledm/PyOmniTS/exp/exp_main.py", line 285, in <dictcomp>
    batch = {k: v.to(f"cuda:{self.configs.gpu_id}") for k, v in batch.items()}
  File "/mnt/projects/zhuangyo_project/khaledm/new_conda_environment/new_environment/lib/python3.10/site-packages/torch/cuda/__init__.py", line 412, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
Stack (most recent call last):
  File "/mnt/home/khaledm/PyOmniTS/main.py", line 105, in <module>
    logger.exception(f"{e}", stack_info=True)
